#  Numpy 


### Numpy functions

Numpy is a Python library used to perform mathematical operations with multidimensional arrays and matrices.

- np.reshape
- np.matmul
- np.linspace
- np.repeat
- np.arange

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [31]:
import numpy as np

In [21]:
# List of functions explained 
function1 = np.reshape  # (this function is used to change and array's shape and keeping the data)
function2 = np.matmul # (this function is used to perform multiplication on matrices values)
function3 = np.linspace # (this function is used to create an evenly spaced array with a specified interval)
function4 = np.repeat # (this function is used to create an array with specified number of repeated values )
function5 = np.arange # (this function is used to create an evenly spaced array with specified steps and interval)

## Function 1 - np.reshape

When you want to change an array's shape using numpy, just use this function.

In [22]:
# Example 1 
arr0 = np.array([11, 12, 13, 13, 14, 15, 15, 16, 17, 17, 18, 19.5])
print(f'this an array: {arr0}')
matrix0 = arr0.reshape(2, 2, 3)
print(f'this an matrix: {matrix0}')

this an array: [11.  12.  13.  13.  14.  15.  15.  16.  17.  17.  18.  19.5]
this an matrix: [[[11.  12.  13. ]
  [13.  14.  15. ]]

 [[15.  16.  17. ]
  [17.  18.  19.5]]]


In [28]:
# Example 2 - working
arr1 = np.array([[ 1, 5, 2],
                 [ 2, 6, 5],
                 [ 3,  7, 9],
                 [4, 8, 10]])
print(arr1)
arr1.shape

[[ 1  5  2]
 [ 2  6  5]
 [ 3  7  9]
 [ 4  8 10]]


(4, 3)

In [24]:
arr1_reshaped = arr1.reshape(3,4)
print(arr1_reshaped)
arr1_reshaped.shape

[[ 1  5  2  2]
 [ 6  5  3  7]
 [ 9  4  8 10]]


(3, 4)

In [25]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 9])
arr_reshaped = arr.reshape(3,3)
print(arr_reshaped)

ValueError: cannot reshape array of size 8 into shape (3,3)

I tried to reshape and array that is an 1d array with 8 elements to an 2d matrix with 3 rows and 3 columns (3x3 = 9 elements). 
To visualize what I did wrong:
[[1,2,3] n\
[4,5,6] n\
[7,9, ]] n\
It's missing one last value and consequently will raise an error.

In [26]:
#To fix this error, you either can delete or add one value from the 1d array and you can change the dimensions as well:
arr.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 9]])

## Function 2 - np.matmul

This function can be used when you want to perform multiplication on matrices

In [32]:
# Example 1 - working
arr1 = np.array([[ 1, 5, 2],
                 [ 2, 6, 5],
                 [ 3, 7, 9],
                 [4, 8, 10]])
arr2 = np.array([ 1, 10, 2])
np.matmul(arr1, arr2)

array([ 55,  72,  91, 104])

In [33]:
# Example 2 - working
arr4 = np.array([[1,0],[0,1]])
arr5 = np.array([[4,1],[2,2]]) 
np.matmul(arr4, arr5)

array([[4, 1],
       [2, 2]])

In [34]:
# Example 3 - breaking (to illustrate when it breaks)
arr6 = np.array([[1, 2],
                 [0, 1]])
arr7 = np.array([1, 2, 3])
np.matmul(arr6,arr7)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

The error raised because I tried to perform an multiplication on an array with 3 elements and a matrix with dimensions 2x2. As the ValueError says, 3 is different from 2 and we have no value to multiply with the number 3.

## Function 3 - ???

Add some explanations

In [ ]:
# Example 1 - working
???

Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

## Function 4 - ???

Add some explanations

In [ ]:
# Example 1 - working
???

Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

## Function 5 - ???

Add some explanations

In [ ]:
# Example 1 - working
???

Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...