> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


#  Numpy 


### Numpy functions

Numpy is a Python library used to perform mathematical operations with multidimensional arrays and matrices.

- np.reshape
- np.matmul
- np.linspace
- np.repeat
- np.arange

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [2]:
!pip install jovian --upgrade -q

In [3]:
import jovian

In [4]:
jovian.commit(project='5 numpy functions - learning numpy begginer friendly')

<IPython.core.display.Javascript object>

[jovian] Creating a new project "anajulia22/5 numpy functions - learning numpy begginer friendly"
[jovian] Committed successfully! https://jovian.com/anajulia22/5-numpy-functions-learning-numpy-begginer-friendly


'https://jovian.com/anajulia22/5-numpy-functions-learning-numpy-begginer-friendly'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [5]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.reshpe  # (this function is used to change and array's shape and keeping the data)
function2 = np.matmul # (this function is used to perform multiplication on matrices values)
function3 = np.linspace # (this function is used to create an evenly spaced array with a specified interval)
function4 = np.repeat # (this function is used to create an array with specified number of repeated values )
function5 = np.arange # (this function is used to create an evenly spaced array with specified steps and interval)

## Function 1 - np.reshape

When you want to change an array's shape using numpy, just use this function.

In [19]:
# Example 1 
arr0 = np.array([11, 12, 13, 13, 14, 15, 15, 16, 17, 17, 18, 19.5])
print(f'this an array: {arr0}')
matrix0 = arr0.reshape(2, 2, 3)
print(f'this an matrix: {matrix0}')

this an array: [11.  12.  13.  13.  14.  15.  15.  16.  17.  17.  18.  19.5]
this an matrix: [[[11.  12.  13. ]
  [13.  14.  15. ]]

 [[15.  16.  17. ]
  [17.  18.  19.5]]]


In [28]:
# Example 2 - working
arr1 = np.array([[ 1, 5,  2],
       [ 2, 6,  5],
       [ 3,  7,  9],
       [4, 8, 10]])
print(arr1)
arr1.shape


[[ 1  5  2]
 [ 2  6  5]
 [ 3  7  9]
 [ 4  8 10]]


(4, 3)

In [30]:
arr1_reshaped = arr1.reshape(3,4)
print(arr1_reshaped)
arr1_reshaped.shape

[[ 1  5  2  2]
 [ 6  5  3  7]
 [ 9  4  8 10]]


(3, 4)

Explanation about example

In [35]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 9])
arr_reshaped = arr.reshape(3,3)
print(arr_reshaped)

ValueError: cannot reshape array of size 8 into shape (3,3)

I tried to reshape and array that is an 1d array with 8 elements to an 2d matrix with 3 rows and 3 columns (3x3 = 9 elements). 
To visualize what I did wrong:
[[1,2,3] n\
[4,5,6] n\
[7,9, ]] n\
It's missing one last value and consequently will raise an error.


In [34]:
#To fix this error, you either can delete or add one value from the 1d array and you can change the dimensions as well:
arr.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 9]])

In [36]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "anajulia22/5-numpy-functions-learning-numpy-begginer-friendly" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/anajulia22/5-numpy-functions-learning-numpy-begginer-friendly


'https://jovian.com/anajulia22/5-numpy-functions-learning-numpy-begginer-friendly'

## Function 2 - np.matm

This function can be used when you want to perform multiplication on matrices

In [ ]:
# Example 1 - working
???

Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [32]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 3 - ???

Add some explanations

In [ ]:
# Example 1 - working
???

Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [26]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 4 - ???

Add some explanations

In [ ]:
# Example 1 - working
???

Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [27]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 5 - ???

Add some explanations

In [ ]:
# Example 1 - working
???

Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [28]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>